### ISSUE TITLE
Migrate to Gradle Metadata for dependency reports

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/config#82]
https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-1.0-specification.md

We may need to still produce `pom.xml` alongside with `.module` files in order to use GitHub dependency analysis features.

See also a related request #81.

**Comment by yuri-sergiichuk** [comment]
The `.module` files are published automatically by the Gradle publishing plugin. I believe we're publishing them since the migration to Gradle 6.x a while ago. At least it is available for all `base` versions starting from `1.3` in the Maven [repo](https://spine.mycloudrepo.io/public/repositories/releases/io/spine/spine-base/1.3.0/).

@alexander-yevsyukov do you think we can close the issue or the idea was to hand-craft a metadata file for the whole repository?
